// ABOUTME: Bundles command-hook composer shims for Claude Code and Codex.
// ABOUTME: Inlines card policy modules and local hook-policy helpers with Bun.

import { rm } from "node:fs/promises";
import { join } from "node:path";
import type { Runtime } from "../hook-policy/types";
import { writeAtomically } from "../fs";
import { DRWN_VERSION } from "../version";

export interface HookPolicyBundleInput {
  cardName: string;
  policyName: string;
  policyTsPath: string;
}

export interface BundleHookComposerOptions {
  runtime: Extract<Runtime, "claude-code" | "codex">;
  policies: HookPolicyBundleInput[];
  outputDir: string;
}

function toImportPath(pathValue: string) {
  return JSON.stringify(pathValue);
}

function safeIdentifier(cardName: string, policyName: string, index: number) {
  return `policy_${index}_${cardName}_${policyName}`.replace(/[^A-Za-z0-9_$]/g, "_");
}

function renderLogger() {
  return `const logger = {
  warn(data, message) {
    process.stderr.write(JSON.stringify({ level: "warn", message, data }) + "\\n");
  },
  error(data, message) {
    process.stderr.write(JSON.stringify({ level: "error", message, data }) + "\\n");
  },
};`;
}

function renderEntrypoint(runtime: BundleHookComposerOptions["runtime"], policies: HookPolicyBundleInput[]) {
  const decodeName = runtime === "claude-code" ? "decodeClaudeEvent" : "decodeCodexEvent";
  const encodeName = runtime === "claude-code" ? "encodeForClaude" : "encodeForCodex";
  const policyImports = policies.map((policy, index) => {
    const id = safeIdentifier(policy.cardName, policy.policyName, index);
    return `import ${id} from ${toImportPath(policy.policyTsPath)};`;
  });
  const policyIds = policies.map((policy, index) => safeIdentifier(policy.cardName, policy.policyName, index));

  return `// Generated by drwn; do not edit.
import { composeToolHooks } from "darwinian-mind/hook-policy";
import { ${decodeName} } from ${toImportPath(join(import.meta.dir, "decode-event.ts"))};
import { ${encodeName} } from ${toImportPath(join(import.meta.dir, "encode-decision.ts"))};
${policyImports.join("\n")}

${renderLogger()}

const policies = [${policyIds.join(", ")}];
const composed = composeToolHooks(policies, { runtime: ${JSON.stringify(runtime)}, logger });

function readStdin() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => { data += chunk; });
    process.stdin.on("end", () => resolve(data));
  });
}

(async () => {
  const stdin = await readStdin();
  const payload = stdin.trim().length > 0 ? JSON.parse(stdin) : {};
  const phase = payload.hook_event_name === "PostToolUse" ? "post-tool" : "pre-tool";
  const event = ${decodeName}(payload, phase);
  const decision = phase === "pre-tool"
    ? await composed.beforeToolCall(event)
    : (await composed.afterToolCall(event), undefined);
  const encoded = ${runtime === "claude-code" ? `${encodeName}(decision, event)` : `${encodeName}(decision, event, logger)`};
  if (encoded) {
    process.stdout.write(encoded);
  }
})().catch((error) => {
  process.stderr.write(error instanceof Error ? error.stack ?? error.message : String(error));
  process.exit(1);
});
`;
}

function hookPolicyResolverPlugin() {
  return {
    name: "drwn-hook-policy-resolver",
    setup(build: { onResolve: (options: { filter: RegExp }, callback: () => { path: string }) => void }) {
      build.onResolve({ filter: /^darwinian-mind\/hook-policy$/ }, () => ({
        path: join(import.meta.dir, "..", "hook-policy", "index.ts"),
      }));
    },
  };
}

export async function bundleHookComposer(options: BundleHookComposerOptions): Promise<string> {
  const entryPath = join(options.outputDir, ".drwn-composer-entry.ts");
  const composerPath = join(options.outputDir, "composer.mjs");
  await writeAtomically(entryPath, renderEntrypoint(options.runtime, options.policies));
  try {
    const buildConfig = {
      entrypoints: [entryPath],
      target: "node",
      format: "esm",
      write: false,
      plugins: [hookPolicyResolverPlugin()],
    } as Parameters<typeof Bun.build>[0] & { write: false };
    const result = await Bun.build(buildConfig);
    if (!result.success) {
      const logs = result.logs.map((log) => log.message).join("\n");
      throw new Error(`Failed to bundle hook composer:\n${logs}`);
    }
    const output = result.outputs[0];
    if (!output) {
      throw new Error("Failed to bundle hook composer: Bun produced no output");
    }
    const bundled = await output.text();
    await writeAtomically(composerPath, `// Generated by drwn; do not edit.\n// drwn-version: ${DRWN_VERSION}\n${bundled}`);
    return composerPath;
  } finally {
    await rm(entryPath, { force: true });
  }
}
