// ABOUTME: Emits Mastra TypeScript hook composer modules.
// ABOUTME: Leaves bundling to the consuming Mastra application toolchain.

import { join } from "node:path";
import { writeAtomically } from "../fs";
import { DRWN_VERSION } from "../version";
import type { HookPolicyBundleInput } from "./bundle-composer";

export interface EmitMastraComposerOptions {
  policies: HookPolicyBundleInput[];
  outputDir: string;
}

function safeIdentifier(cardName: string, policyName: string, index: number) {
  return `policy_${index}_${cardName}_${policyName}`.replace(/[^A-Za-z0-9_$]/g, "_");
}

function renderMastraComposer(policies: HookPolicyBundleInput[]) {
  const imports = policies.map((policy, index) => {
    const id = safeIdentifier(policy.cardName, policy.policyName, index);
    return `import ${id} from ${JSON.stringify(policy.policyTsPath)};`;
  });
  const ids = policies.map((policy, index) => safeIdentifier(policy.cardName, policy.policyName, index));

  return `// Generated by drwn; do not edit.
// drwn-version: ${DRWN_VERSION}
${imports.join("\n")}

export const policies = [${ids.join(", ")}];

export { composeToolHooks } from "darwinian-harness/hook-policy";
`;
}

export async function emitMastraComposer(options: EmitMastraComposerOptions): Promise<string> {
  const composerPath = join(options.outputDir, "composer.ts");
  await writeAtomically(composerPath, renderMastraComposer(options.policies));
  return composerPath;
}
